### ISSUE TITLE
USER STORY: Sign In

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#11]
As a **Site User** I can **sign in with my email and password** so that **I can publish a recipe, comment, like, and rate any recipe**

**Acceptance Criteria:**

- The Sign-in option should appear on the navigation bar
- The option should be available for only non-authenticated users
- The user should be able to log in using Gmail and Facebook accounts
- The user should also be able to see and fill the form (email and password fields) to sign in
- After successfully signing in, the Logout option should appear on the navigation bar
- Sign Up and Sign In option should be removed from the navigation bar
- Appropriate message should be displayed to the user

**Tasks:**

- [ ] Customize AbstractUser class to use email rather than username
- [ ] Use Django Allauth and Oauth for social account authentication
- [ ] Create a custom user model and register in admins.py 
- [ ] Customize the log in page
