### ISSUE TITLE
USER STORY: Rate recipes

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#13]
As a **Site User** I can **rate recipes** so that **I can help other users to choose the right content**

**Acceptance Criteria:**

- The site user who is logged in should be able to see the rating option
- The user should be able to rate between 1-5
- The average rating should be updated accordingly

**Tasks**:

- [ ]  Add a rating model in models.py
- [ ]  Add a rating method in the recipe model to calculate the average rating
- [ ]  Add a rating icon and display the average rating in the full_recipe, recipes template
- [ ]  Create a view to update the average rating accordingly
- [ ]  Add a URL path
