### ISSUE TITLE
USER STORY: Navigation/Header

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#15]
As a **Site User** I can **navigate to different pages** so that **I can explore the whole website**

**Acceptance Criteria:**

- The header should be at the top of the page
- The header should contain the website logo and title
- By clicking on the logo and title the user should be redirected to the home page
- The navigation bar should be placed after the header
- The links of the navigation bar should redirect to the corresponding pages
- The navigation bar links should change according to the user authentication

**Tasks:**

- [ ] Use bootstrap nav element with collapsable nav bar for smaller screen
- [ ] Add custom CSS
- [ ] Put the links in the "href" attribute of each nav bar items
