### ISSUE TITLE
USER STORY: Alert messages

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#16]
As a **Site User** I can **view an alert message** so that **I know whether the actions were successful or not**

**Acceptance Criteria:**

- An appropriate message should be displayed after every action
- The alert message should have an option to close it
- The alert message should also get closed after a certain time

**Tasks:**

- [ ]  Add Bootstrap alert messages into base.html
- [ ]  Add message tags into settings.py
- [ ]  Create a timeout function for alert messages
