### ISSUE TITLE
USER STORY: Recipe cards list

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#17]
As a **Site User** I can **view recipe cards on the home page** so that **I can select one to read**

**Acceptance Criteria:**

- The recipe cards with recipe image, average rating, number of likes and comments should be displayed on the home page
- The recipe should be in order of highest average rating
- The recipe cards should be clickable for all users

**Tasks:**

- [ ] Use HTML, CSS, and bootstrap to create cards in the recipe template
- [ ] Create a view to render this template
- [ ] Call average rating and number of like functions
- [ ] Add URL path
