### ISSUE TITLE
USER STORY: Read full recipe

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#18]
As a **Site User** I can **click on a recipe card** so that **I can read the full recipe**

**Acceptance Criteria:**

- The user should be able to click on the recipe name link in the recipe card
- The link should redirect to the full recipe page
- The full recipe page should contain the recipe image, title, author name, category, method,
   ingredients, instructions, cook time, prep time, calories, likes, ratings, and comments

**Tasks:**

- [ ] Create a full recipe template using HTML, CSS, and bootstrap
- [ ] Create a view to render the template 
- [ ] Add URL path
