### ISSUE TITLE
USER STORY: Choose Category

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#22]
As a **Site User** I can **select the category** so that **I can choose what type of recipe I want to see**

**Acceptance Criteria:**

-  The categories should be displayed at the bottom of the home page after the recipe cards
-  The user should be able to click on the categories
-  The selected category should redirect the user to a filtered recipe page of that category

**Tasks:**

- [ ] Create category buttons using HTML, CSS, and Bootstrap on recipes template
- [ ] Create a view to render the template
- [ ] Add URL path
