### ISSUE TITLE
USER STORY: Choose method

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#23]
As a **Site User** I can **select the method** so that **I can choose what type of recipe I want to see**

**Acceptance Criteria:**

-  The methods should be displayed at the bottom of the home page after the recipe cards and category buttons
-  The user should be able to click on the methods
-  The selected method should redirect the user to a filtered recipe page of that method

**Tasks:**

- [ ] Create method buttons using HTML, CSS, and Bootstrap on recipes template
- [ ] Create a view to render the template
- [ ] Add URL path
