### ISSUE TITLE
USER STORY: Manage posts

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#3]
As a **Site Admin** I can **create, read, update, and delete posts** so that **I can manage my blog content**

**Acceptance Criteria:**

- The site admin should be able to **_create_** a new recipe blog
- The site admin should be able to **_read_** all the recipe blogs
- The site admin should be able to **_update_** any blog as needed
- The site admin should be able to **_delete_** any blog if needed

**Tasks:**

- [ ] Create the model for blogs in models.py
- [ ] Register the model in admin.py
- [ ] Create a super user
- [ ] Log in to the admin page using the superuser account
- [ ] Test the CRUD functionality
