### ISSUE TITLE
USER STORY: Approve comments

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#4]
As a **Site Admin** I can **approve or disapprove comments** so that **I can filter out any inappropriate content**

**Acceptance Criteria:**

- The admin should be able to **_approve/review comments_** before it is displayed on the main recipe page

**Tasks:**

- [ ] Create a comment model with a value of 'approved' set to False
- [ ] Register the comment model in admins.py
- [ ] Go to the admin page to test the functionality
