### ISSUE TITLE
USER STORY: Footer social media links

### ISSUE THREAD

**Issue by Sadaf-Tariq** [Sadaf-Tariq/pp4-desi-recipe-blog#5]
As a **Site User** I can **click on social media links** so that **I can stay updated by following the platform**

**Acceptance Criteria:**

- Icons with **_social media_** links are displayed in the footer
- The links should be opened in different tabs

**Tasks:**

- [ ] Create a footer using HTML, CSS, and bootstrap 
- [ ] Add social media links in the "href" attribute
- [ ] Add "target=_blank"
